// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {main} from '../models';

export function AnalyzeAllDiariesEmotion(arg1:boolean,arg2:string):Promise<Record<string, any>>;

export function AnalyzeDiaryEmotion(arg1:string,arg2:boolean,arg3:string):Promise<app.EmotionAnalysisResult>;

export function AuthenticateUser(arg1:string,arg2:string):Promise<app.AuthResult>;

export function AuthenticateWithBiometric(arg1:string):Promise<app.AuthResult>;

export function CheckAuthStatus():Promise<main.AuthStatusResult>;

export function CheckBiometricSupport():Promise<app.BiometricInfo>;

export function CheckMigrationStatus():Promise<app.MigrationStatus>;

export function CreateDiary(arg1:string,arg2:string):Promise<app.Diary>;

export function CreateDiaryWithEncryption(arg1:string,arg2:string,arg3:app.DiaryEncryptionOptions):Promise<app.Diary>;

export function CreateFirstUser(arg1:string,arg2:string):Promise<app.AuthResult>;

export function DisableBiometric():Promise<void>;

export function EnableBiometric(arg1:string):Promise<void>;

export function GetCurrentUser():Promise<app.User>;

export function GetDiariesList():Promise<Array<app.Diary>>;

export function GetDiaryByID(arg1:string):Promise<app.Diary>;

export function GetDiaryEmotionAnalysis(arg1:string):Promise<app.EmotionAnalysis>;

export function GetDiaryEncryptionInfo(arg1:string):Promise<app.DiaryEncryptionInfo>;

export function GetDiaryWithPassword(arg1:string,arg2:string):Promise<app.Diary>;

export function GetEmotionAnalysisHistory():Promise<Array<app.EmotionAnalysis>>;

export function GetFirstUser():Promise<app.User>;

export function GetUserEmotionStatistics(arg1:number):Promise<Record<string, any>>;

export function GetUserEmotionTrends(arg1:number):Promise<Array<app.EmotionAnalysis>>;

export function Greet(arg1:string):Promise<string>;

export function Logout():Promise<void>;

export function MigrateData():Promise<void>;

export function SearchDiaries(arg1:string):Promise<Array<app.Diary>>;

export function SearchDiariesWithContext(arg1:string):Promise<Array<app.SearchResult>>;

export function UpdateDiary(arg1:app.Diary):Promise<void>;

export function UpdateDiaryWithEncryption(arg1:app.Diary,arg2:app.DiaryEncryptionOptions):Promise<void>;

export function UploadDiary(arg1:string,arg2:Array<number>):Promise<app.Diary>;
