// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiariesList() {
  return window['go']['main']['App']['GetDiariesList']();
}

export function GetDiaryByID(arg1) {
  return window['go']['main']['App']['GetDiaryByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveDiary(arg1) {
  return window['go']['main']['App']['SaveDiary'](arg1);
}

export function UploadDiary(arg1, arg2) {
  return window['go']['main']['App']['UploadDiary'](arg1, arg2);
}
