// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDiary(arg1, arg2) {
  return window['go']['main']['App']['CreateDiary'](arg1, arg2);
}

export function GetDiariesList() {
  return window['go']['main']['App']['GetDiariesList']();
}

export function GetDiaryByID(arg1) {
  return window['go']['main']['App']['GetDiaryByID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SearchDiaries(arg1) {
  return window['go']['main']['App']['SearchDiaries'](arg1);
}

export function SearchDiariesWithContext(arg1) {
  return window['go']['main']['App']['SearchDiariesWithContext'](arg1);
}

export function UpdateDiary(arg1) {
  return window['go']['main']['App']['UpdateDiary'](arg1);
}

export function UploadDiary(arg1, arg2) {
  return window['go']['main']['App']['UploadDiary'](arg1, arg2);
}
