// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateUser(arg1, arg2) {
  return window['go']['main']['App']['AuthenticateUser'](arg1, arg2);
}

export function AuthenticateWithBiometric(arg1) {
  return window['go']['main']['App']['AuthenticateWithBiometric'](arg1);
}

export function CheckAuthStatus() {
  return window['go']['main']['App']['CheckAuthStatus']();
}

export function CheckBiometricSupport() {
  return window['go']['main']['App']['CheckBiometricSupport']();
}

export function CheckMigrationStatus() {
  return window['go']['main']['App']['CheckMigrationStatus']();
}

export function CreateDiary(arg1, arg2) {
  return window['go']['main']['App']['CreateDiary'](arg1, arg2);
}

export function CreateDiaryWithEncryption(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDiaryWithEncryption'](arg1, arg2, arg3);
}

export function CreateFirstUser(arg1, arg2) {
  return window['go']['main']['App']['CreateFirstUser'](arg1, arg2);
}

export function DisableBiometric() {
  return window['go']['main']['App']['DisableBiometric']();
}

export function EnableBiometric(arg1) {
  return window['go']['main']['App']['EnableBiometric'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDiariesList() {
  return window['go']['main']['App']['GetDiariesList']();
}

export function GetDiaryByID(arg1) {
  return window['go']['main']['App']['GetDiaryByID'](arg1);
}

export function GetDiaryEncryptionInfo(arg1) {
  return window['go']['main']['App']['GetDiaryEncryptionInfo'](arg1);
}

export function GetDiaryWithPassword(arg1, arg2) {
  return window['go']['main']['App']['GetDiaryWithPassword'](arg1, arg2);
}

export function GetFirstUser() {
  return window['go']['main']['App']['GetFirstUser']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MigrateData() {
  return window['go']['main']['App']['MigrateData']();
}

export function SearchDiaries(arg1) {
  return window['go']['main']['App']['SearchDiaries'](arg1);
}

export function SearchDiariesWithContext(arg1) {
  return window['go']['main']['App']['SearchDiariesWithContext'](arg1);
}

export function TestBiometricAPI() {
  return window['go']['main']['App']['TestBiometricAPI']();
}

export function UpdateDiary(arg1) {
  return window['go']['main']['App']['UpdateDiary'](arg1);
}

export function UpdateDiaryWithEncryption(arg1, arg2) {
  return window['go']['main']['App']['UpdateDiaryWithEncryption'](arg1, arg2);
}

export function UploadDiary(arg1, arg2) {
  return window['go']['main']['App']['UploadDiary'](arg1, arg2);
}
