// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CreateDiary(arg1:string,arg2:string):Promise<app.Diary>;

export function GetDiariesList():Promise<Array<app.Diary>>;

export function GetDiaryByID(arg1:string):Promise<app.Diary>;

export function Greet(arg1:string):Promise<string>;

export function UpdateDiary(arg1:app.Diary):Promise<void>;

export function UploadDiary(arg1:string,arg2:Array<number>):Promise<app.Diary>;
